apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  labels:
    app: consumer-app
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
      - name: consumer-app
        image: egemmell/devops-main_consumer_app
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: consumer-app
spec:
  selector:
    app: consumer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer