apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-app
  labels:
    app: producer-app
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: producer-app
  template:
    metadata:
      labels:
        app: producer-app
    spec:
      containers:
      - name: producer-app
        image: egemmell/devops-main_producer_app
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: consumer-app
spec:
  selector:
    app: consumer-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer